services:
  - type: web
    name: cinelog
    runtime: ruby
    plan: free
    buildCommand: bundle install && bundle exec rails assets:precompile
    preDeployCommand: bundle exec rails db:migrate db:seed
    startCommand: bundle exec puma -C config/puma.rb
    envVars:
      - key: RAILS_ENV
        value: production
      - key: SECRET_KEY_BASE
        generateValue: true
      - key: RAILS_SERVE_STATIC_FILES
        value: true
      - key: RAILS_LOG_TO_STDOUT
        value: true
      - key: TMDB_API_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: cinelog-db
          property: connectionString

databases:
  - name: cinelog-db
    plan: free
    databaseName: cinelog_production
